### PR TITLE
Added the check if ETW collector can be run.

### LINKED ISSUE #12: Error in DiagnosticAssembly.Execute(string argument)
I try execute sample code from Open file and I get error:

Merge operation failed return code 0x2

Script execution failed: System.ApplicationException: Merge operation failed return code 0x2
   w Microsoft.Diagnostics.Tracing.Session.TraceEventSession.Merge(String[] inputETLFileNames, String outputETLFileName, TraceEventMergeOptions options)
   w Microsoft.Diagnostics.Tracing.Session.TraceEventSession.MergeInPlace(String etlFileName, TextWriter log)
   w Tune.Core.Collectors.ClrEtwCollector.Stop() w C:\TestAndOtherStuff\TUNE\Tune.Core\Collectors\ClrEtwCollector.cs:wiersz 62
   w Tune.Core.Collectors.ClrEtwCollector.Dispose() w C:\TestAndOtherStuff\TUNE\Tune.Core\Collectors\ClrEtwCollector.cs:wiersz 159
   w Tune.Core.DiagnosticAssembly.Execute(String argument) w C:\TestAndOtherStuff\TUNE\Tune.Core\DiagnosticAssembly.cs:wiersz 75

### LINKED ISSUE #14: Check if current process is elevated
By using `TraceEventSession.IsElevated()` check whether current process has rights to configure and use ETW sessions. Warning should be provided to the user if it is not.

### PR DESCRIPTION
**Pull request by pawlos**
Fixes #12 and resolves #14.

### CODE REVIEW

**Comment by pawlos** [comment]
@kkokosa I can see some publishing artifacts error. Is it something that my change did? Could it be related to yesterday's github problems?

Should I fix something?

**Comment by kkokosa** [comment]
I have no idea why it is failing... So strange that it may be related to those problems indeed. I've rerun the build and we will see.

**Comment by kkokosa** [comment]
@pawlos manually it builds successfully, re-run does not work. Let's treat it all as intermittent and merge this :)

**Comment by ptrstpp950** [comment]
The problem is in AzureDevOps. You have to implement 2 build definitions. One for master repo and one for PR. Check more at dotnetomaniak blog (https://blog.dotnetomaniak.pl/CI-CD-dotnetomaniaka-czyli-Azure-DevOps-w-praktyce/)

**Pull request merged**
